### ISSUE TITLE
Change footer color

### ISSUE THREAD

**Issue by AlexFloresVeliz** [AlexFloresVeliz/open-source#5]
The footer looks pretty weird all bright red. It doesn't match very well with the rest of the page. Change the colors in `style.css` to something less funky.

*You have full creative freedom. There is no wrong answer to this issue. Only tacky choices.*

**Comment by AlexErling** [comment]
Hi, I am new to open source. Can I take this on?

**Comment by AlexFloresVeliz** [comment]
Hello @AlexErling! Really appreciate you taking the time to work on these issues :)
